#!/bin/bash

# 4 x 4 keyboard matrix setup script
# Author : David Lublink
# License : GPLv2+


cd /sys/class/gpio/

# Columns :

echo 4 > export
echo out > gpio4/direction
echo 0 > gpio4/active_low

echo 17 > export
echo out > gpio17/direction
echo 0 > gpio17/active_low

echo 27 > export
echo out > gpio27/direction
echo 0 > gpio27/active_low

echo 22 > export
echo out > gpio22/direction
echo 0 > gpio22/active_low

# Rows

echo 18 > export
echo in > gpio18/direction
echo 0 > gpio18/active_low

echo 23 > export
echo in > gpio23/direction
echo 0 > gpio23/active_low

echo 24 > export
echo in > gpio24/direction
echo 0 > gpio24/active_low

echo 25 > export
echo in > gpio25/direction
echo 0 > gpio25/active_low

