#!/usr/bin/php
<?php

# 4 x 4 keyboard matrix setup script
# Author : David Lublink
# Note : This script scans the given 4x4 matrix and outputs to the console on each key press
# License : GPLv2+

# Keyboard matrix setup 
/*
======= 23 25  18  24 =======
gpio27  1   2   3   4
gpio17  4   5   6   B
gpio22  7   8   9   C
gpio4   *   0   #   D
*/
// GPIO pins belonging to rows
$rows = [ 27, 17, 22, 4 ];
// GPIO pins belonging to columns
$columns = [ 23, 25, 18, 24 ];

$grid = [];
$grid[] = [ '1', '2', '3', 'A' ];
$grid[] = [ '4', '5', '6', 'B' ];
$grid[] = [ '7', '8', '9', 'C' ];
$grid[] = [ '*', '0', '#', 'D' ];

define( 'GPIO', '/sys/class/gpio' );


echo "\n\n\n";
echo "Output ===> ";

$ts = time() + 30;
while( $ts > time() )
{
	// Scan the rows
	foreach ( $rows as $row )
	{
		// turn on the $row output
		on( $row );

		// now go to each column on the row to find the output
		foreach ( $columns as $column )	
		{
			// is is a reserved word and isGPIOPinOn($column ) seemed a bit much
			if ( iss( $column ) )
				echo what( $row, $column ) ;
		}
		//turn off output
		off( $row );
	}
	usleep(10000);
}

function what ( $row, $column )
{
	global $rows, $columns, $grid ;

	$ridx = array_search( $row, $rows );
	$cidx = array_search( $column, $columns );

	// wait until button is released
	while( iss( $column ) ) usleep( 50000 ); 

	return $grid[$ridx][$cidx] ;
}                      
                       
function on( $row )
{
	file_put_contents( GPIO . '/gpio'. $row .'/value', 1 );
}

function iss ( $column )
{
	return trim( file_get_contents( GPIO . '/gpio'. $column .'/value') ) === '1';

}

function off( $row )
{
	file_put_contents( GPIO . '/gpio'. $row .'/value', 0 );
}

